# Generated by Django 5.0.6 on 2024-07-12 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='pagada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='factura',
            name='direccion',
            field=models.CharField(max_length=30),
        ),
    ]
