# Generated by Django 5.0.6 on 2024-07-12 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_factura_pagada_alter_factura_direccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='pagada',
            new_name='pagado',
        ),
    ]
