# Generated by Django 5.0.6 on 2024-07-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_articulo_valor_total_alter_articulo_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='valor_total',
        ),
        migrations.AlterField(
            model_name='articulo',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
