# Generated by Django 5.0.6 on 2024-07-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_remove_articulo_valor_total_alter_articulo_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
